# Generated by Django 4.1.7 on 2023-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_author_id_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_bio',
        ),
        migrations.AddField(
            model_name='author',
            name='author_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
