# Generated by Django 4.1.7 on 2023-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
