# Generated by Django 4.1.7 on 2023-04-26 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrow_back_date_alter_borrow_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 26, 13, 55, 22, 431594)),
        ),
    ]
