# Generated by Django 4.1.7 on 2023-03-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_result_result_maths_result_value_error_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['-id']},
        ),
    ]
